// The single most dangerous thing about the PHP-to-Node port: if the Node
// bcrypt library cannot read the hashes PHP already wrote, every existing
// account is locked out of their journal permanently.
//
// PHP's password_hash() emits the "$2y$" prefix. bcryptjs emits "$2b$". The two
// prefixes name the same algorithm, but that is the sort of thing you verify
// rather than believe, so both directions are pinned here against real hashes
// generated by a real PHP.
import assert from 'node:assert';
import bcrypt from 'bcryptjs';

// Generated by PHP's password_hash(). Regenerate with:
//   php -r 'echo password_hash("correct horse battery staple", PASSWORD_DEFAULT);'
// Cost 10 is what php:8.3 (the Railway container) produced for PASSWORD_DEFAULT;
// cost 12 is what newer PHP produces. Rows in journal_users may hold either.
const PHP_VECTORS = [
  {
    label: 'PASSWORD_DEFAULT on php 8.3 (cost 10)',
    password: 'hunter2hunter2',
    hash: '$2y$10$JADfV1wag9.vHl8pONW8uOps/9RBHp24h/PhDT8Z9BclrDwGMRtWK',
  },
  {
    label: 'PASSWORD_DEFAULT on php 8.5 (cost 12)',
    password: 'correct horse battery staple',
    hash: '$2y$12$VRlMilbxDY5s4a3BWoa6ounI4S4L3MujBXa7V3o63N4RmEFUnNm1K',
  },
];

// --- Reading: existing $2y$ hashes must still verify -------------------------

for (const { label, password, hash } of PHP_VECTORS) {
  assert.ok(hash.startsWith('$2y$'), `${label}: fixture must be a $2y$ hash`);

  assert.strictEqual(
    await bcrypt.compare(password, hash),
    true,
    `${label}: bcryptjs must verify the password PHP hashed — otherwise this user is locked out`,
  );

  assert.strictEqual(
    await bcrypt.compare(`${password}x`, hash),
    false,
    `${label}: a wrong password must not verify`,
  );
  assert.strictEqual(await bcrypt.compare('', hash), false, `${label}: empty password must not verify`);
}

// The cost is read from the hash itself, so a cost-12 row keeps its cost-12
// work factor and is never silently weakened on login.
assert.strictEqual(PHP_VECTORS[0].hash.slice(4, 6), '10');
assert.strictEqual(PHP_VECTORS[1].hash.slice(4, 6), '12');

// --- Writing: new hashes must stay readable by PHP too -----------------------
// This is the rollback guarantee. trade_handler.php is still in the repo; if the
// port is reverted, accounts registered or reset on Vercel must still log in.
//
// bcryptjs writes "$2b$". The router rewrites that to "$2y$" before storing, so
// the password_hash column stays uniform with every row PHP wrote. Both forms
// verify under PHP — checked directly against php 8.5:
//   password_verify('hunter2hunter2', '$2b$10$ZfZfE6Ko…') === true
//   password_verify('hunter2hunter2', '$2y$10$ZfZfE6Ko…') === true

const written = await bcrypt.hash('a new password', 10);
assert.match(written, /^\$2b\$10\$/, 'bcryptjs writes $2b$ at the cost we asked for');

// The exact rewrite api/_lib/router.js performs.
const stored = `$2y$${written.slice(4)}`;
assert.match(stored, /^\$2y\$10\$/, 'stored hashes carry the $2y$ prefix PHP wrote');
assert.strictEqual(stored.length, written.length, 'the rewrite must not change the hash length');
assert.strictEqual(stored.slice(4), written.slice(4), 'only the prefix changes — never the salt or digest');

assert.strictEqual(await bcrypt.compare('a new password', stored), true, 'the rewritten hash still verifies');
assert.strictEqual(await bcrypt.compare('a new passworD', stored), false);
assert.strictEqual(await bcrypt.compare('a new password', written), true);

// A $2b$ hash produced by bcryptjs, confirmed to verify under PHP's
// password_verify(). Pinned so a future library swap that stops reading it —
// and would therefore break rollback — fails here.
assert.strictEqual(
  await bcrypt.compare('hunter2hunter2', '$2b$10$ZfZfE6Koc4xxiaXC/O4WB.Oi7Oz9yKEwEbbWRQw0.QeVrxRMNESAe'),
  true,
);
// Same hash, prefix rewritten to $2y$: identical algorithm, so it must also
// verify. This is why no prefix translation is needed in either direction.
assert.strictEqual(
  await bcrypt.compare('hunter2hunter2', '$2y$10$ZfZfE6Koc4xxiaXC/O4WB.Oi7Oz9yKEwEbbWRQw0.QeVrxRMNESAe'),
  true,
);

// --- Malformed input must not throw or pass ---------------------------------
for (const bad of ['', 'not-a-hash', '$2y$', '$2y$10$tooshort']) {
  let result;
  try {
    result = await bcrypt.compare('hunter2hunter2', bad);
  } catch {
    result = false; // throwing is acceptable; verifying is not
  }
  assert.strictEqual(result, false, `malformed hash ${JSON.stringify(bad)} must never verify`);
}

console.log('bcryptCompat.check.mjs: all assertions passed');
